language: node_js
node_js:
- '8'
- '7'
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- yarn lint
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: S7xH5GiHktX9o8s12ZZSv12qpbLsCjQbu7iWPq1AdYzmVtCfQUk7sdsPCPVD+cy/hTbqfxCGripCawxX0J4NErdUzmkugv736ymGwZjAZ6r6G3kp8aKTqdqzgO1FGwnaDJqqa0wnvYE/bW7I02mb8VPcTIzMtjG0DRCHDMq5LLWclQcBOwwHHXSr9U+YYEFxfa9cSAuAXgDWvpie8ZVGoQtxEPO0Ah5/0rmEudRWyBGuoIgvxsfISfJwks07LcKBitE1QpIfBW2PGfsuJRT4AYz5U2h92crOVP+NKoVOkH2uswSc4Vd4JD3sQhMp9ZNYATf90D3CkvIJGq/Z/e3K30iSZvkjviajEZGCnhXopUmzzzf4mlO5gD0Mn5ObhKZjNnVlELAJ5EvkVZcRFMk6UyIzmBAqSKh6wXq5sZrbFh/3fcZp1sdaS7+LDw5mFriJ6Q/hMX6hiGnpittktG92RM/bSKG1vGgiUe/XoNH/U3hYy80UMcCh1OGsnJ1tebcpCpyn3kEdVujvNSihVr+xmKKhWt3GBR+qAm3r6BXCY18HCx5pRGwDTZPFimWX5bcIkHsZPpqWgD+xYuDoWDaWpvrYUZBMymV82a9g3fd3e43UTwLZdadS7xI5gzlCYXrfQe5ecgdfBPrf30nsI6MkM4Tsuj3gqnZKjf4LR1cCi4s=
  app: foxweb
  on:
    repo: foxleigh81/foxweb
    branch: foxweb
