language: node_js
node_js: stable
before_script:
  - npm install -g gulp
script: gulp build --prod
deploy:
  provider: heroku
  api_key:
    secure: eNqy8DcJgVy4tAtCfo1sbJ9nwnU1ir8ZisMECi0r7/t5lmQDHigAlnw6m1H/DjNf68jOC1Z4+ZYhnqAkenG9FFAALgbXEIvfPnvRZVpnW9NMK+L3V+0sQPzCwKvz4AqApGFGj1ec0UhOLv/5TitrhB9EYo/uaQFr7CYhG/3SeCIz01n8WtYc5RZbiqVBWPt436/cGABj5ia2+M8K3zMictVl7uL3c7dxU47Mz6hCgMBrH6ZYZFM5rSl5W8Kj922zHM+TwgnvIUwnnNhUz2rSQ7N1aOXQABPo7Mhdt3X27/vrgUdeCVdXveATYFKYBsvjXXLXww8d79SGzX4zR1BTWCt82Q1g3cfUjtfMk5IGBeKYJxk2OT6Rh3rT8M/hFOma5Nw5yiMd+4WIbRv3enRQSWR9oKSJurzRUP8DScuDgfwAdSo3Hd1mJsayCG/JKmZmf6IyZVfjJmHEZG0WlxW/UPzr592TuvvGBQii4k9B86Ysffr8HAi/6hz1kI4XB7x3UtfQaEJvpXdWH99eDk/u2xLgiCTdGDHwu3SUVCya9wecGT9epH61I3fdBaTZb8ZzMjeIlvFWoxA8mADjH32QiESGwTT/i274tp7V6x4hKdIRpA7EfeyusAwY1WGLMcNlBrkht608Qv9+SyIfRuMe2HEcp/kcGiYJUCrJgdEEkUA=
  app: foxweb
  on:
    repo: foxleigh81/foxweb
    branch: foxweb
